### ISSUE TITLE
Do you have standard pipeline SRP-AR-Mirror-Sample?

### ISSUE THREAD

**Issue by zhuxiaol** [akillimum/Unity3d-Universal-SRP-AR-Mirror-Sample#1]
Hi, I have bought your standard pipeline mirror package "https://assetstore.unity.com/packages/vfx/shaders/legacy-mirror-shaders-and-post-effects-81728". Do you have SPR-AR-Mirror-Sample used this package?

**Comment by akillimum** [comment]
No sorry, is there a problem when you try to implement that?
