### ISSUE TITLE
Depth Blur Issue

### ISSUE THREAD

**Issue by zhuxiaol** [akillimum/Unity3d-Universal-SRP-AR-Mirror-Sample#2]
I try to enable the depth blur and choose blursdepth.shader. 
In unity game window, I can see that the reflection changes by "depth blur cutoff".
But when I run on the android phone(Note10+), there is no reflection.
It is so strange!

**Comment by akillimum** [comment]
Hi, as stated in docs (Bugs and Issues), depth blur does not work on mobile (most of them). Cause it uses heavy calculations and some other card specific shader codes. Even it works, it can kill your fps :)
